# Generated by Django 5.1.1 on 2024-09-24 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
